version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8082"
    env_file:
      - app.env
    volumes:
      - ./logs:/app/logs
    links:
      - redis
  redis:
    image: redis:alpine
